### PR TITLE
171 number view headers

### PR DESCRIPTION
**Pull request by ayya-vimala**
This is in conjunction with another PR in Buddhanexus for the matching backend.
This might not be the best way to do it but I could not get an adequately sorted object/dictionary out of the backend so if you feel it can be done better, please delete these two PR.

Also removing old jsons because the correct ones are on buddhanexus.
Also adding a dash in the regex so it will accept filenames with a dash in it.

Also did issue 170 on this branch: small change to have it load all the parallels in the table.

### CODE REVIEW

**Comment by TrebuhD** [comment]
@ayya-vimala what language should the labels be in? They're displaying in chinese on the tibetan page for me. Is that the desired behavior?

**Comment by TrebuhD** [comment]
Is this the correct order? (screenshot from this branch)

image

**Comment by ayya-vimala** [comment]
This is very strange ... it is completely different from when I pushed it before. I will check it out.
You had changed the language for the header tables in another PR and I have not touched that and when I pushed this, that was okay.

**Comment by ayya-vimala** [comment]
Okay ... got it: ordering is correct but after pulling the branch you first have to do a `make load-data` on that branch to load the category-numbers for ordering. Than the order should be okay.
The labels however are indeed not. Will have a look.

**Comment by TrebuhD** [comment]
I pushed a change to the backend PR that rendered some of this code unnecessary, so I removed it. I checked it and it looks good!

**Pull request merged**
